# Generated by Django 2.0.7 on 2018-09-10 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptno', models.CharField(max_length=44)),
                ('clash', models.BooleanField(default=0)),
                ('rc', models.BooleanField(default=0)),
                ('booked', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptno', models.CharField(max_length=44)),
                ('p1name', models.CharField(max_length=44)),
                ('p1email', models.EmailField(max_length=44)),
                ('p2name', models.CharField(max_length=44)),
                ('clash', models.BooleanField(default=0)),
                ('rc', models.BooleanField(default=0)),
                ('cday', models.BooleanField(default=0)),
                ('rday', models.BooleanField(default=0)),
                ('cslot', models.IntegerField(default=0)),
                ('rslot', models.IntegerField(default=0)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
