# Generated by Django 2.0.2 on 2018-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashFriday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptno', models.CharField(max_length=44)),
                ('p1name', models.CharField(max_length=44)),
                ('p1email', models.EmailField(max_length=44)),
                ('p2name', models.CharField(max_length=44)),
                ('slot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClashSaturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptno', models.CharField(max_length=44)),
                ('p1name', models.CharField(max_length=44)),
                ('p1email', models.EmailField(max_length=44)),
                ('p2name', models.CharField(max_length=44)),
                ('slot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RCFriday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptno', models.CharField(max_length=44)),
                ('p1name', models.CharField(max_length=44)),
                ('p1email', models.EmailField(max_length=44)),
                ('p2name', models.CharField(max_length=44)),
                ('slot', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='cday',
            new_name='booked',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cslot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rday',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rslot',
        ),
    ]
